name: ShotGrid Toolkit Workflow

on:
  workflow_call:
    inputs:
      is-prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: true

jobs:
  release:
    name: Create Release
    uses: ./.github/workflows/release-to-github.yml
    secrets: inherit
    with:
      is-prerelease: ${{ inputs.is-prerelease }}