on:
  workflow_call:
    inputs:
      use-base-version:
          description: 'Whether to use the base version or not'
          required: false
          type: boolean
          default: false
    outputs:
      version:
          description: 'The new version number'
          value: ${{ jobs.increment_version.outputs.version }}

jobs:
  increment_version:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      version: ${{ steps.set_job_output.outputs.version }}

    steps:
      - name: Increment version with base version
        if:  ${{ inputs.use-base-version == 'true' }}
        id: sgtk_version_increment
        uses: ./.github/workflows/sgtk-version-increment.yml

      - name: Increment version
        if:  ${{ inputs.use-base-version == 'false' }}
        id: version_increment
        uses: Falcons-Creative-Group/version-increment@2023.10.2
        with:
          scheme: semver
          increment: patch

      - name: Set job output
        id: set_job_output
        run: |
          if ${{ inputs.use-base-version }}; then
            echo "version=${{ steps.sgtk_version_increment.outputs.version }}" >> $GITHUB_ENV
            echo "::set-output name=version::${{ steps.sgtk_version_increment.outputs.version }}"
          else
            echo "version=${{ steps.version_increment.outputs.version }}" >> $GITHUB_ENV
            echo "::set-output name=version::${{ steps.version_increment.outputs.version }}"

      - name: Print version
        run: echo "version=${{ steps.set_job_output.outputs.version }}"